spring:
  datasource:
    url: jdbc:mysql://localhost:3307/springNNDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    filter:
      order: -100
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 92a59b1194e2be42632e7cc1ce946c1b630913f40c0b5e96d275f44230325e4f1871852f2a418be6c6c3b3f69cb176bb67c0eab88c60de0139130753c28fb5e9
  expiration: 86400000

flyway:
  locations: classpath:db.migration
  baseline-on-migrate: true