# Configurações do banco de dados
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springNNDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configurações do JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# JWT Secret
jwt:
  secret: senhasegura

# Configurações do Flyway
flyway:
  locations: classpath:db.migration
  baseline-on-migrate: true
